package com.thomasjbarrerasconsulting.faces.kotlin.facedetector

import com.thomasjbarrerasconsulting.faces.R
import com.thomasjbarrerasconsulting.faces.kotlin.FaceBreakApplication

class ClassifierText {
    companion object{
        fun get(label:String): String {
            val context = FaceBreakApplication.instance

            return when (label){
                "Central and South America"	->	context.getString(R.string.central_and_south_america)
                "China"	->	context.getString(R.string.china)
                "East Africa (Somalia, Kenya, Ethiopia, Eritrea)"	->	context.getString(R.string.east_africa)
                "Eastern Europe (Poland, Czech Republic, Romania, Bulgaria, Russia)"	->	context.getString(R.string.eastern_europe)
                "England"	->	context.getString(R.string.england)
                "Ireland, Scotland and Wales"	->	context.getString(R.string.ireland)
                "Japan and Korea"	->	context.getString(R.string.japan_and_korea)
                "North Africa and the Middle East"	->	context.getString(R.string.north_africa)
                "North America"	->	context.getString(R.string.north_america)
                "North India"	->	context.getString(R.string.north_india)
                "Polynesia"	->	context.getString(R.string.polynesia)
                "Scandinavia"	->	context.getString(R.string.scandinavia)
                "South India"	->	context.getString(R.string.south_india)
                "Southeast Asia (Vietnam, Cambodia, Thailand, Indonesia)"	->	context.getString(R.string.southeast_asia)
                "Southern Europe (Spain, Italy, Greece and the Balkans)"	->	context.getString(R.string.southern_europe)
                "West Africa (Nigeria, Ghana, Congo, Angola, Namibia)"	->	context.getString(R.string.west_africa)
                "Western Europe (France and Germany)"	->	context.getString(R.string.western_europe)
                "Adorable"	->	context.getString(R.string.adorable)
                "Angelic"	->	context.getString(R.string.angelic)
                "Beautiful"	->	context.getString(R.string.classically_beautiful)
                "Compassionate"	->	context.getString(R.string.compassionate)
                "Creative"	->	context.getString(R.string.creative)
                "Free Spirited"	->	context.getString(R.string.free_spirited)
                "Honest"	->	context.getString(R.string.honest)
                "Kind"	->	context.getString(R.string.kind)
                "Naturally Beautiful"	->	context.getString(R.string.naturally_beautiful)
                "Passionate"	->	context.getString(R.string.passionate)
                "Resourceful"	->	context.getString(R.string.resourceful)
                "Responsible"	->	context.getString(R.string.responsible)
                "Rugged"	->	context.getString(R.string.rugged)
                "Strong"	->	context.getString(R.string.strong)
                "Virtuous"	->	context.getString(R.string.virtuous)
                "Wise"	->	context.getString(R.string.wise)
                "Bossy"	->	context.getString(R.string.bossy)
                "Confused"	->	context.getString(R.string.confused)
                "Cranky"	->	context.getString(R.string.cantankerous)
                "Flirty"	->	context.getString(R.string.flirty)
                "Grumpy"	->	context.getString(R.string.grumpy)
                "Impulsive"	->	context.getString(R.string.impulsive)
                "Irritating"	->	context.getString(R.string.irritating)
                "Lazy"	->	context.getString(R.string.lazy)
                "Melodramatic"	->	context.getString(R.string.melodramatic)
                "Pompous"	->	context.getString(R.string.pompous)
                "Proud"	->	context.getString(R.string.proud)
                "Rebellious"	->	context.getString(R.string.rebellious)
                "Spoiled"	->	context.getString(R.string.spoiled)
                "Timid"	->	context.getString(R.string.anxious)
                "Uninhibited"	->	context.getString(R.string.uninhibited)
                "Vain"	->	context.getString(R.string.vain)
                "Wild"	->	context.getString(R.string.wild)
                "Blue Eyes"	->	context.getString(R.string.blue_eyes)
                "Brown Eyes"	->	context.getString(R.string.brown_eyes)
                "Closed Eyes"	->	context.getString(R.string.closed_eyes)
                "Green Eyes"	->	context.getString(R.string.green_eyes)
                "Grey Eyes"	->	context.getString(R.string.grey_eyes)
                "Pure Blue Eyes"	->	context.getString(R.string.pure_blue)
                "Pure Brown Eyes"	->	context.getString(R.string.pure_brown)
                "Pure Green Eyes"	->	context.getString(R.string.pure_green)
                "Pure Grey Eyes"	->	context.getString(R.string.pure_grey)
                "Trace Blue Eyes"	->	context.getString(R.string.trace_blue)
                "Trace Brown Eyes"	->	context.getString(R.string.trace_brown)
                "Trace Green Eyes"	->	context.getString(R.string.trace_green)
                "Trace Grey Eyes"	->	context.getString(R.string.trace_grey)
                "Angry"	->	context.getString(R.string.angry)
                "Disgusted"	->	context.getString(R.string.disgusted)
                "Happy"	->	context.getString(R.string.happy)
                "Sad"	->	context.getString(R.string.sad)
                "Scared"	->	context.getString(R.string.scared)
                "Serious"	->	context.getString(R.string.serious)
                "Silly"	->	context.getString(R.string.silly)
                "Stern"	->	context.getString(R.string.stern)
                "Surprised"	->	context.getString(R.string.surprised)
                "Suspicious"	->	context.getString(R.string.suspicious)
                "Male"	->	context.getString(R.string.male)
                "Female"	->	context.getString(R.string.female)
                "Diamond"	->	context.getString(R.string.diamond)
                "Heart"	->	context.getString(R.string.heart)
                "Oblong"	->	context.getString(R.string.oblong)
                "Oval"	->	context.getString(R.string.oval)
                "Pear"	->	context.getString(R.string.pear)
                "Round"	->	context.getString(R.string.round)
                "Square"	->	context.getString(R.string.square)
                "Strong Diamond"	->	context.getString(R.string.strong_diamond)
                "Strong Heart"	->	context.getString(R.string.strong_heart)
                "Strong Oblong"	->	context.getString(R.string.strong_oblong)
                "Strong Oval"	->	context.getString(R.string.strong_oval)
                "Strong Pear"	->	context.getString(R.string.strong_pear)
                "Strong Round"	->	context.getString(R.string.strong_round)
                "Strong Square"	->	context.getString(R.string.strong_square)
                "Very Strong Diamond"	->	context.getString(R.string.very_strong_diamond)
                "Very Strong Heart"	->	context.getString(R.string.very_strong_heart)
                "Very Strong Oblong"	->	context.getString(R.string.very_strong_oblong)
                "Very Strong Oval"	->	context.getString(R.string.very_strong_oval)
                "Very Strong Pear"	->	context.getString(R.string.very_strong_pear)
                "Very Strong Round"	->	context.getString(R.string.very_strong_round)
                "Very Strong Square"	->	context.getString(R.string.very_strong_square)
                "Slightly Diamond"	->	context.getString(R.string.slightly_diamond)
                "Slightly Heart"	->	context.getString(R.string.slightly_heart)
                "Slightly Oblong"	->	context.getString(R.string.slightly_oblong)
                "Slightly Oval"	->	context.getString(R.string.slightly_oval)
                "Slightly Pear"	->	context.getString(R.string.slightly_pear)
                "Slightly Round"	->	context.getString(R.string.slightly_round)
                "Slightly Square"	->	context.getString(R.string.slightly_square)
                "Unlike Diamond"	->	context.getString(R.string.unlike_diamond)
                "Unlike Heart"	->	context.getString(R.string.unlike_heart)
                "Unlike Oblong"	->	context.getString(R.string.unlike_oblong)
                "Unlike Oval"	->	context.getString(R.string.unlike_oval)
                "Unlike Pear"	->	context.getString(R.string.unlike_pear)
                "Unlike Round"	->	context.getString(R.string.unlike_round)
                "Unlike Square"	->	context.getString(R.string.unlike_square)
                "Very Unlike Heart"	->	context.getString(R.string.very_unlike_heart)
                "Very Unlike Oblong"	->	context.getString(R.string.very_unlike_oblong)
                "Very Unlike Oval"	->	context.getString(R.string.very_unlike_oval)
                "Very Unlike Pear"	->	context.getString(R.string.very_unlike_pear)
                "Very Unlike Round"	->	context.getString(R.string.very_unlike_round)
                "Very Unlike Square"	->	context.getString(R.string.very_unlike_square)
                "Bald"	->	context.getString(R.string.no_hair_detected)
                "Black"	->	context.getString(R.string.black)
                "Blond"	->	context.getString(R.string.blond)
                "Blue"	->	context.getString(R.string.blue)
                "Brown"	->	context.getString(R.string.brown)
                "Green"	->	context.getString(R.string.green)
                "Grey"	->	context.getString(R.string.grey)
                "Neon Red"	->	context.getString(R.string.neon_red)
                "Orange"	->	context.getString(R.string.orange)
                "Pink"	->	context.getString(R.string.pink)
                "Purple"	->	context.getString(R.string.purple)
                "Red"	->	context.getString(R.string.red)
                "White"	->	context.getString(R.string.white)
                "Yellow"	->	context.getString(R.string.yellow)
                "Afro"	->	context.getString(R.string.afro)
                "Bob"	->	context.getString(R.string.bob)
                "Braided Pig Tails"	->	context.getString(R.string.braided_pig_tails)
                "Braids"	->	context.getString(R.string.braids)
                "Buzz Cut"	->	context.getString(R.string.buzz_cut)
                "Curly"	->	context.getString(R.string.curly)
                "Hair Bun"	->	context.getString(R.string.hair_bun)
                "Head Covered"	->	context.getString(R.string.head_covered)
                "Long"	->	context.getString(R.string.long_hair)
                "Men's Medium"	->	context.getString(R.string.mens_medium)
                "Mohawk"	->	context.getString(R.string.mohawk)
                "Mullet"	->	context.getString(R.string.mullet)
                "Pig Tails"	->	context.getString(R.string.pig_tails)
                "Pixie"	->	context.getString(R.string.pixie)
                "Women's Medium"	->	context.getString(R.string.womens_medium)
                "Women's Short"	->	context.getString(R.string.womens_short)
                "Baseball Cap"	->	context.getString(R.string.baseball_cap)
                "Clear"	->	context.getString(R.string.clear)
                "Cowboy Hat"	->	context.getString(R.string.cowboy_hat)
                "Hat"	->	context.getString(R.string.hat)
                "Headscarf"	->	context.getString(R.string.headscarf)
                "Medium Eyebrows"	->	context.getString(R.string.medium_eyebrows)
                "No Eyebrows"	->	context.getString(R.string.no_eyebrows)
                "Thick Eyebrows"	->	context.getString(R.string.thick_eyebrows)
                "Thin Eyebrows"	->	context.getString(R.string.thin_eyebrows)
                "Acne"	->	context.getString(R.string.acne)
                "Beard"	->	context.getString(R.string.beard)
                "Dark Lips"	->	context.getString(R.string.dark_lips)
                "Dimples"	->	context.getString(R.string.dimples)
                "Freckles"	->	context.getString(R.string.freckles)
                "Full Lips"	->	context.getString(R.string.full_lips)
                "Goatee"	->	context.getString(R.string.goatee)
                "Mask"	->	context.getString(R.string.mask)
                "Moustache"	->	context.getString(R.string.moustache)
                "Pink Lips"	->	context.getString(R.string.pink_lips)
                "Red Lips"	->	context.getString(R.string.red_lips)
                "Stubble"	->	context.getString(R.string.stubble)
                "Bindi"	->	context.getString(R.string.bindi)
                "Earrings"	->	context.getString(R.string.earrings)
                "Glasses"	->	context.getString(R.string.glasses)
                "Sunglasses"	->	context.getString(R.string.sunglasses)

                else -> context.getString(R.string.unknown)
            }
        }
    }
}